const fs = require('fs');


var buffer = fs.readFileSync('./postleitzahlen-deutschland.geojson'); 

var geojson = JSON.parse(buffer);
var plzs = {}
geojson["features"].map(feature => {
    if (!feature) return;
    plzs[feature.properties.plz] = {
        // sieht hässlich aus, macht die Datei aber von ~570kb zu 499kb
        "n": feature.properties.note,
        "l": feature.properties.geo_point_2d,
        //"plz": feature.properties.plz 
    };
});
fs.writeFileSync("../static/js/plz.js",
`// auto generated by extract_plz.js, do not edit
var plzs = ${JSON.stringify({plzs})}`
);